accounts/urls.py
from django.urls import path
from accounts.views import students, teachers


app_name = 'accounts'

urlpatterns = [
	# path('home/', teachers.home_view, name='home'),
	path('login/student/', students.login_view, name='student-login'),
	path('login/teacher/', teachers.login_view, name='teacher-login'),
	path('logout/teacher/', teachers.logout_view, name='logout-teacher'),
	path('logout/student/', students.logout_view, name='logout-student'),
	#path('home_students', students.home_view, name='home'),
	path('signup/teachers/', teachers.TeacherSignupView.as_view(), name='teacher_signup'),
	path('signup/students/', students.StudentSignupView, name='student_signup'),
]

clearance_system/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
	path('admin/', admin.site.urls),
	path('accounts/', include('accounts.urls')),
    path('departments/', include('departments.urls')),
    path('students/', include('students.urls')),
]

departments/urls.py
from django.urls import path
from .views import *

app_name = 'departments'

urlpatterns = [
path('', UploadView, name='upload'),
path('1/<str:slug>/', LibraryFormView, name='add-form-library'),
path('2/<str:slug>/', WorkshopFormView, name='add-form-workshop'),
path('3/<str:slug>/', MustSoFormView, name='add-form-mustso'),
path('4/<str:slug>/', LaboratoriesFormView, name='add-form-laboratories'),
path('5/<str:slug>/', HeadOfDepartmentFormView, name='add-form-hod'),
path('6/<str:slug>/', CateringOfficeFormView, name='add-form-catering-office'),
path('7/<str:slug>/', SportsGamesFormView, name='add-form-sports-games'),
path('8/<str:slug>/', AccomodationFormView, name='add-form-accomodation'),
path('9/<str:slug>/', AccountsOfficeFormView, name='add-form-accounts-office'),
path('library/<str:slug>/<str:item>/', library_search, name='library-search'),
path('workshop/<str:slug>/<str:item>/', workshop_search, name='workshop-search'),
path('mustso/<str:slug>/<str:item>/', mustso_search, name='mustso-search'),
path('laboratories/<str:slug>/<str:item>/', laboratories_search, name='laboratories-search'),
path('head-of-department/<str:slug>/<str:item>/', hod_search, name='hod-search'),
path('catering-office/<str:slug>/<str:item>/', catering_office_search, name='catering-office-search'),
path('sports-games/<str:slug>/<str:item>/', sports_games_search, name='sports-games-search'),
path('accomodation/<str:slug>/<str:item>/', accomodation_search, name='accomodation-search'),
path('accounts-office/<str:slug>/<str:item>/', accounts_office_search, name='accounts-office-search'),
path('dos/', dos_view, name='dos-requests'),
path('accounts-officer/', accounts_officer_view, name='accounts-officer'),
path('dou/', dou_view, name='dou')
]

departments/models.py
from django.db import models
from accounts.models import Student

class MustSo(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	item = models.CharField(max_length=50)
	lent_date = models.DateField(auto_now=True)

	def __str__(self):
		return f"{self.student}"


class Library(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	item = models.CharField(max_length=50)
	lent_date = models.DateField(auto_now=True)

	def __str__(self):
		return f"{self.student}"


class Workshop(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	item = models.CharField(max_length=50)
	lent_date = models.DateField(auto_now=True)

	def __str__(self):
		return f"{self.student}"


class Laboratories(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	item = models.CharField(max_length=50)
	lent_date = models.DateField(auto_now=True)

	def __str__(self):
		return f"{self.student}"


class HeadOfDepartment(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	item = models.CharField(max_length=50)
	lent_date = models.DateField(auto_now=True)

	def __str__(self):
		return f"{self.student}"


class CateringOffice(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	item = models.CharField(max_length=50)
	lent_date = models.DateField(auto_now=True)

	def __str__(self):
		return f"{self.student}"


class SportsGames(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	item = models.CharField(max_length=50)
	lent_date = models.DateField(auto_now=True)

	def __str__(self):
		return f"{self.student}"


class Accomodation(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	item = models.CharField(max_length=50)
	lent_date = models.DateField(auto_now=True)

	def __str__(self):
		return f"{self.student}"


class AccountsOffice(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	item = models.CharField(max_length=50)
	lent_date = models.DateField(auto_now=True)

	def __str__(self):
		return f"{self.student}"


class DeanOfStudents(models.Model):
	student = models.OneToOneField(Student, on_delete=models.CASCADE, primary_key=True)
	approved = models.BooleanField(default=False)

	def __str__(self):
		return f"{self.student}"	

departments/forms.py
from django import forms
from .models import *

class LibraryForm(forms.ModelForm):

	class Meta:
		model = Library
		fields = ['student','item']


class WorkshopForm(forms.ModelForm):

	class Meta:
		model = Workshop
		fields = ['student', 'item']


class MustSoForm(forms.ModelForm):

	class Meta:
		model = MustSo
		fields = ['student', 'item']


class LaboratoriesForm(forms.ModelForm):

	class Meta:
		model = Laboratories
		fields = ['student', 'item']


class HeadOfDepartmentForm(forms.ModelForm):

	class Meta:
		model = HeadOfDepartment
		fields = ['student', 'item']


class CateringOfficeForm(forms.ModelForm):

	class Meta:
		model = CateringOffice
		fields = ['student', 'item']								


class SportsGamesForm(forms.ModelForm):

	class Meta:
		model = SportsGames
		fields = ['student', 'item']


class AccomodationForm(forms.ModelForm):

	class Meta:
		model = Accomodation
		fields = ['student', 'item']


class AccountsOfficeForm(forms.ModelForm):

	class Meta:
		model = AccountsOffice
		fields = ['student', 'item']

departments/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
# from accounts.decorators import teacher_required
from .decorators import *
from .forms import *
from accounts.models import Student, User
from django.db.models import Q
from .models import *
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.contrib import messages


# @login_required
@teacher_required
def UploadView(request):
	template_name = 'departments/form.html'
	return render(request, template_name)

################### Form Views ##########################
@library_officer_required
def LibraryFormView(request,slug):
	if request.method == 'POST':
		form = LibraryForm(request.POST or None)
		if form.is_valid():
			student = form.cleaned_data.get('student')
			if student.request:
				messages.info(request, f'This student is not permitted in lending an item')
			else:	
				form.save()
			return redirect('departments:add-form-library',slug)
	else:
		form = LibraryForm()

	context = { 'form': form }
	template_name = 'departments/upload.html'
	return render(request,template_name, context)


@workshop_officer_required
def WorkshopFormView(request,slug):
	if request.method == 'POST':
		form = WorkshopForm(request.POST or None)
		if form.is_valid():
			student = form.cleaned_data.get('student')
			if student.request:
				messages.info(request, f'This student is not permitted in lending an item')
			else:	
				form.save()
			return redirect('departments:add-form-workshop',slug)
	else:
		form = WorkshopForm()

	context = { 'form': form }
	template_name = 'departments/upload.html'
	return render(request,template_name, context)


@mustso_officer_required
def MustSoFormView(request,slug):
	if request.method == 'POST':
		form = MustSoForm(request.POST or None)
		if form.is_valid():
			student = form.cleaned_data.get('student')
			if student.request:
				messages.info(request, f'This student is not permitted in lending an item')
			else:	
				form.save()
			return redirect('departments:add-form-mustso',slug)
	else:
		form = MustSoForm()

	context = { 'form': form }
	template_name = 'departments/upload.html'
	return render(request,template_name, context)


@laboratories_officer_required
def LaboratoriesFormView(request,slug):
	if request.method == 'POST':
		form = LaboratoriesForm(request.POST or None)
		if form.is_valid():
			student = form.cleaned_data.get('student')
			if student.request:
				messages.info(request, f'This student is not permitted in lending an item')
			else:	
				form.save()
			return redirect('departments:add-form-laboratories',slug)
	else:
		form = LaboratoriesForm()

	context = { 'form': form }
	template_name = 'departments/upload.html'
	return render(request,template_name, context)


@hod_officer_required
def HeadOfDepartmentFormView(request,slug):
	if request.method == 'POST':
		form = HeadOfDepartmentForm(request.POST or None)
		if form.is_valid():
			student = form.cleaned_data.get('student')
			if student.request:
				messages.info(request, f'This student is not permitted in lending an item')
			else:	
				form.save()
			return redirect('departments:add-form-hod',slug)
	else:
		form = HeadOfDepartmentForm()

	context = { 'form': form }
	template_name = 'departments/upload.html'
	return render(request,template_name, context)


@catering_officer_required
def CateringOfficeFormView(request,slug):
	if request.method == 'POST':
		form = CateringOfficeForm(request.POST or None)
		if form.is_valid():
			student = form.cleaned_data.get('student')
			if student.request:
				messages.info(request, f'This student is not permitted in lending an item')
			else:	
				form.save()
			return redirect('departments:add-form-catering-office',slug)
	else:
		form = CateringOfficeForm()

	context = { 'form': form }
	template_name = 'departments/upload.html'
	return render(request,template_name, context)


@sports_games_officer_required
def SportsGamesFormView(request,slug):
	if request.method == 'POST':
		form = SportsGamesForm(request.POST or None)
		if form.is_valid():
			student = form.cleaned_data.get('student')
			if student.request:
				messages.info(request, f'This student is not permitted in lending an item')
			else:	
				form.save()
			return redirect('departments:add-form-sports-games',slug)
	else:
		form = SportsGamesForm()

	context = { 'form': form }
	template_name = 'departments/upload.html'
	return render(request,template_name, context)


@accomodation_officer_required
def AccomodationFormView(request,slug):
	if request.method == 'POST':
		form = AccomodationForm(request.POST or None)
		if form.is_valid():
			student = form.cleaned_data.get('student')
			if student.request:
				messages.info(request, f'This student is not permitted in lending an item')
			else:	
				form.save()
			return redirect('departments:add-form-accomodation',slug)
	else:
		form = AccomodationForm()

	context = { 'form': form }
	template_name = 'departments/upload.html'
	return render(request,template_name, context)


@accountsoffice_officer_required
def AccountsOfficeFormView(request,slug):
	if request.method == 'POST':
		form = AccountsOfficeForm(request.POST or None)
		if form.is_valid():
			student = form.cleaned_data.get('student')
			if student.request:
				messages.info(request, f'This student is not permitted in lending an item')
			else:	
				form.save()
			return redirect('departments:add-form-accounts-office',slug)
	else:
		form = AccountsOfficeForm()

	context = { 'form': form }
	template_name = 'departments/upload.html'
	return render(request,template_name, context)



################### Searching Views ######################
@library_officer_required
def library_search(request,slug, item):
	# user = request.user.departmentofficer.department_name
	# print(user)

	ctx = {}
	url_parameter = request.GET.get('q')
	if url_parameter:
		students = Library.objects.filter(Q(student__user__first_name__icontains=url_parameter) | Q(student__user__last_name__icontains=url_parameter))
	else:
		students = ''


	if slug == 'None' and item == 'None' :
		print('pass')
		pass
	else:
		if request.method == 'GET':
			print(slug)
			student = Library.objects.filter(Q(student_id=slug) and Q(item=item))
			student.delete()

	ctx['students'] = students

	if request.is_ajax():
		html = render_to_string(
			template_name='departments/library-results.html',
			context={'students':students}
		)

		data_dict = {"html_from_view": html}

		return JsonResponse(data=data_dict, safe=False)

	return render(request,'departments/search.html',ctx)


@workshop_officer_required
def workshop_search(request, slug, item):
	ctx = {}
	url_parameter = request.GET.get('q')
	if url_parameter:
		students = Workshop.objects.filter(Q(student__user__first_name__icontains=url_parameter) | Q(student__user__last_name__icontains=url_parameter))
	else:
		students = ''

	if slug is None and item is None:
		print('pass')
		pass
	else:
		if request.method == 'GET':
			print(slug)
			student = Workshop.objects.filter(Q(student_id=slug) and Q(item=item))
			student.delete()

	ctx['students'] = students

	if request.is_ajax():
		html = render_to_string(
			template_name='departments/workshop-results.html',
			context={'students':students}
		)

		data_dict = {"html_from_view": html}

		return JsonResponse(data=data_dict, safe=False)

	return render(request,'departments/search.html',ctx)


@mustso_officer_required
def mustso_search(request, slug, item):
	ctx = {}
	url_parameter = request.GET.get('q')
	if url_parameter:
		students = MustSo.objects.filter(Q(student__user__first_name__icontains=url_parameter) | Q(student__user__last_name__icontains=url_parameter))
	else:
		students = ''

	if slug is None and item is None:
		print('pass')
		pass
	else:
		if request.method == 'GET':
			print(slug)
			student = MustSo.objects.filter(Q(student_id=slug) and Q(item=item))
			student.delete()

	ctx['students'] = students

	if request.is_ajax():
		html = render_to_string(
			template_name='departments/mustso-results.html',
			context={'students':students}
		)

		data_dict = {"html_from_view": html}

		return JsonResponse(data=data_dict, safe=False)

	return render(request,'departments/search.html',ctx)


@laboratories_officer_required
def laboratories_search(request, slug, item):
	ctx = {}
	url_parameter = request.GET.get('q')
	if url_parameter:
		students = Laboratories.objects.filter(Q(student__user__first_name__icontains=url_parameter) | Q(student__user__last_name__icontains=url_parameter))
	else:
		students = ''

	if slug is None and item is None:
		print('pass')
		pass
	else:
		if request.method == 'GET':
			print(slug)
			student = Laboratories.objects.filter(Q(student_id=slug) and Q(item=item))
			student.delete()

	ctx['students'] = students

	if request.is_ajax():
		html = render_to_string(
			template_name='departments/laboratories-results.html',
			context={'students':students}
		)

		data_dict = {"html_from_view": html}

		return JsonResponse(data=data_dict, safe=False)

	return render(request,'departments/search.html',ctx)



@hod_officer_required
def hod_search(request, slug, item):
	ctx = {}
	url_parameter = request.GET.get('q')
	if url_parameter:
		students = HeadOfDepartment.objects.filter(Q(student__user__first_name__icontains=url_parameter) | Q(student__user__last_name__icontains=url_parameter))
	else:
		students = ''

	if slug is None and item is None:
		print('pass')
		pass
	else:
		if request.method == 'GET':
			print(slug)
			student = HeadOfDepartment.objects.filter(Q(student_id=slug) and Q(item=item))
			student.delete()

	ctx['students'] = students

	if request.is_ajax():
		html = render_to_string(
			template_name='departments/hod-results.html',
			context={'students':students}
		)

		data_dict = {"html_from_view": html}

		return JsonResponse(data=data_dict, safe=False)

	return render(request,'departments/search.html',ctx)



@catering_officer_required
def catering_office_search(request, slug, item):

templates/departments/accomodation-results.html
{% if students %}			
	<table class="table table-striped">
		  <thead>
		    <tr>
		      <th scope="col">Name</th>
		      <th scope="col">Item</th>
		      <th scope="col">Date</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for student in students %}
		    <tr>
		      <td>{{student}}</td>
		      <td>{{student.item}}</td>
		      <td>{{student.lent_date}}</td>
		      <td>
		      	<form action="{% url 'departments:accomodation-search' slug=student.student_id item=student.item %}" method="GET">   	
		      		{% csrf_token %}
			      	<div class="form-group">
						<button class="btn" type="submit">
							<img class='bp-icon' src="/static/img/bootstrap-icons/trash-fill.svg" alt="trash" width="23" height="23">
						</button>
					</div>
				</form>
		      </td>
		    </tr>
		    {% endfor %}
		  </tbody>
	</table>		
{% else %}
	<p style="margin:10px;">No student found</p>
{% endif %}

templates/departments/approved-students.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags%}


{% block side-nav %}
	<div class="teacher-sidebar">
		{% if user.departmentofficer.department_name == 'Library' %}
		<a href="{% url 'departments:add-form-library' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:library-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>		
		{%elif user.departmentofficer.department_name == 'Workshop'%}
		<a href="{% url 'departments:add-form-workshop' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:workshop-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'MustSo'%}
		<a href="{% url 'departments:add-form-mustso' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:mustso-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Laboratories'%}
		<a href="{% url 'departments:add-form-laboratories' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:laboratories-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Head Of Department'%}
		<a href="{% url 'departments:add-form-hod' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:hod-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Catering Office'%}
		<a href="{% url 'departments:add-form-catering-office' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:catering-office-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Sports and Games'%}
		<a href="{% url 'departments:add-form-sports-games' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:sports-games-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>												
		{%elif user.departmentofficer.department_name == 'Accomodation'%}
		<a href="{% url 'departments:add-form-accomodation' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:accomodation-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Accounts Office'%}
		<a href="{% url 'departments:add-form-accounts-office' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:accounts-office-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Dean Of Students'%}
		<a href="{% url 'departments:dos-requests' %}">Student requests<img src="{% static 'img/bootstrap-icons/people-fill.svg' %}" alt='students' height="25" width="25" style="margin-left:18px;padding-bottom:3px;"></a>
		{%elif user.departmentofficer.department_name == 'Accounts Officer'%}
		<a href="{% url 'departments:accounts-officer' %}">Approved students<img src="{% static 'img/bootstrap-icons/people-fill.svg' %}" alt='students' height="25" width="25" style="margin-left:18px;padding-bottom:3px;"></a>
		{%elif user.departmentofficer.department_name == 'Director Of Undergraduates'%}
		<a href="{% url 'departments:dou' %}">Approved students<img src="{% static 'img/bootstrap-icons/people-fill.svg' %}" alt='students' height="25" width="25" style="margin-left:18px;padding-bottom:3px;"></a>
		{%else%}
			<h2>Unauthorized user</h2>				
		{% endif %}
	</div>
{% endblock %}
{% block content%}
	<table class="table ">
		  <thead>
		    <tr>
		      <th scope="col">Student requests</th>
		      <th scope="col">Course</th>
		    </tr>
		  </thead>
		  <tbody>
		  		{% if students %}
					{% for student in students %}
					<tr>
						<td>{{student}}</td>
						<td>{{student.student.course_name}}</td>
					</tr>
					{% endfor %}
				{% else %}
					<tr>
						<td style="color:grey;">0 Student requests</td>	
					</tr>
				{% endif %}	
		  </tbody>
	</table>		
{% endblock %}

templates/departments/dos.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags%}


{% block side-nav %}
	<div class="teacher-sidebar">
		{% if user.departmentofficer.department_name == 'Library' %}
		<a href="{% url 'departments:add-form-library' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:library-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>		
		{%elif user.departmentofficer.department_name == 'Workshop'%}
		<a href="{% url 'departments:add-form-workshop' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:workshop-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'MustSo'%}
		<a href="{% url 'departments:add-form-mustso' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:mustso-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Laboratories'%}
		<a href="{% url 'departments:add-form-laboratories' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:laboratories-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Head Of Department'%}
		<a href="{% url 'departments:add-form-hod' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:hod-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Catering Office'%}
		<a href="{% url 'departments:add-form-catering-office' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:catering-office-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Sports and Games'%}
		<a href="{% url 'departments:add-form-sports-games' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:sports-games-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>												
		{%elif user.departmentofficer.department_name == 'Accomodation'%}
		<a href="{% url 'departments:add-form-accomodation' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:accomodation-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Accounts Office'%}
		<a href="{% url 'departments:add-form-accounts-office' slug=user.departmentofficer.department_name %}">Add Student<i class="flaticon-follow" style="margin-left: 90px;"></i></a>
		<a href="{% url 'departments:accounts-office-search' slug=None item=None %}">Search Student<i class="flaticon-magnifying-glass" style="margin-left: 70px;"></i></a>
		{%elif user.departmentofficer.department_name == 'Dean Of Students'%}
		<a href="{% url 'departments:dos-requests' %}">Student requests<img src="{% static 'img/bootstrap-icons/people-fill.svg' %}" alt='students' height="25" width="25" style="margin-left:18px;padding-bottom:3px;"></a>
		{%elif user.departmentofficer.department_name == 'Accounts Officer'%}
		<a href="{% url 'departments:accounts-officer' %}">Approved students<img src="{% static 'img/bootstrap-icons/people-fill.svg' %}" alt='students' height="25" width="25" style="margin-left:18px;padding-bottom:3px;"></a>	
		{%elif user.departmentofficer.department_name == 'Director Of Undergraduates'%}
		<a href="{% url 'departments:dou' %}">Approved students<img src="{% static 'img/bootstrap-icons/people-fill.svg' %}" alt='students' height="25" width="25" style="margin-left:18px;padding-bottom:3px;"></a>
		{%else%}
			<h2>Unauthorized user</h2>				
		{% endif %}
	</div>
{% endblock %}
{% block content%}
	<table class="table ">
		  <thead>
		    <tr>
		      <th scope="col">Student requests</th>
		      <th scope="col">Course</th>
		    </tr>
		  </thead>
		  <tbody>
		  		{% if students %}
					{% for student in students %}
					<tr>
						<td>{{student}}</td>
						<td>{{student.course_name}}</td>
					</tr>					
					{% endfor %}
				{% else %}
					<tr>
						<td style="color:grey;">0 Student requests</td>	
					</tr>
				{% endif %}	
		  </tbody>
	</table>
  	<form method="POST">
		{% csrf_token %}
		<div class="form-group">
			<button class="btn-outline-success btn-lg " type="submit">Approve</button>
		</div>		
	</form> 			
{% endblock %}