accounts/urls.py
from django.urls import path
from accounts.views import students, teachers


app_name = 'accounts'

urlpatterns = [
	# path('home/', teachers.home_view, name='home'),
	path('login/student/', students.login_view, name='student-login'),
	path('login/teacher/', teachers.login_view, name='teacher-login'),
	path('logout/teacher/', teachers.logout_view, name='logout-teacher'),
	path('logout/student/', students.logout_view, name='logout-student'),
	#path('home_students', students.home_view, name='home'),
	path('signup/teachers/', teachers.TeacherSignupView.as_view(), name='teacher_signup'),
	path('signup/students/', students.StudentSignupView, name='student_signup'),
]

clearance_system/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
	path('admin/', admin.site.urls),
	path('accounts/', include('accounts.urls')),
    path('departments/', include('departments.urls')),
    path('students/', include('students.urls')),
]

students/urls.py
from django.urls import path
from .views import *

app_name = 'students'

urlpatterns = [
	path('', HomeView, name='student-home'),
	path('update/', ProfileUpdate, name='student-update'),
	path('items/', items_urls, name='items-urls'),
	path('items/library/', library_items, name='library-items' ),
	path('items/workshop/', workshop_items, name='workshop-items' ),
	path('items/mustso/', mustso_items, name='mustso-items' ),
	path('items/laboratories/', laboratories_items, name='laboratories-items' ),
	path('items/head-of-department/', hod_items, name='hod-items' ),
	path('items/catering/', catering_office_items, name='catering-office-items' ),
	path('items/sports-games/', sports_games_items, name='sports-games-items' ),
	path('items/accomodation/', accomodation_items, name='accomodation-items' ),
	path('items/accounts-office/', accounts_office_items, name='accounts-office-items' ),
	path('request/dos', request_dos, name='request-dos')
]

students/models.py
from django.db import models

# Create your models here.

students/forms.py
from django import forms
from accounts.models import User, Student


class UserUpdateForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ['username','first_name','last_name','email']



class ProfileUpdateForm(forms.ModelForm):
	course_name = forms.CharField()
	id_number = forms.CharField()

	class Meta:
		model = Student
		fields = ('course_name','id_number')

accounts/views/students.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect,render
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from ..forms import StudentSignupForm,LoginForm, StudentProfileForm
from ..models import User, Student
from django.contrib import messages

#User = get_user_model()


# class StudentSignupView(CreateView):
# 	model = User
# 	form_class = StudentSignupForm
# 	template_name = 'accounts/signup.html'
	
# 	def get_context_data(self,**kwargs):
# 		kwargs['user_type'] = 'student'
# 		return super().get_context_data(**kwargs)

# 	def form_valid(self,form):
# 		user = form.save()
# 		login(self.request, user)
# 		return redirect('accounts:home')	


def StudentSignupView(request, *args):
	if request.method == 'POST':
		signup_form = StudentSignupForm(request.POST or None)
		profile_form = StudentProfileForm(request.POST or None)
		if signup_form.is_valid() and profile_form.is_valid():
			user = signup_form.save()
			student = profile_form.save(commit=False)
			student.user = user
			student.save()
			messages.success(request, f'Account created for {user.first_name}')
			return redirect('students:student-home')
	else:
		signup_form = StudentSignupForm()
		profile_form = StudentProfileForm()

	template_name = 'accounts/signup.html'
	context = {'signup_form' : signup_form, 'profile_form': profile_form }
	return render(request, template_name, context)

			

# @login_required
# def home_view(request):
# 	return render(request,'students/home.html')


def login_view(request):
	form = LoginForm(request.POST or None)
	if request.method == 'POST': 
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(request, username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect('students:student-home')
			else:
				print("User not found")	
	return render(request, 'accounts/login.html',{ 'form': form})		

def logout_view(request):
	logout(request)
	return redirect('accounts:student-login')	



#message.debug
#message.info
#message.success
#message.warning
#message.error

students/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import ProfileUpdateForm, UserUpdateForm
from django.contrib import messages
from .decorators import student_required
from departments.models import *
from accounts.models import Student
from departments.models import *


cleared = ''

@login_required
@student_required
def HomeView(request):
	user = request.user
	student = Student.objects.get(user=user)
	library_items = len(Library.objects.all().filter(student_id=user.id))
	workshop_items = len(Workshop.objects.all().filter(student_id=user.id))
	mustso_items = len(MustSo.objects.all().filter(student_id=user.id))
	laboratories_items = len(Laboratories.objects.all().filter(student_id=user.id))
	hod_items = len(HeadOfDepartment.objects.all().filter(student_id=user.id))
	catering_office_items = len(CateringOffice.objects.all().filter(student_id=user.id))
	sports_games_items = len(SportsGames.objects.all().filter(student_id=user.id))
	accomodation_items = len(Accomodation.objects.all().filter(student_id=user.id))
	accounts_office_items = len(AccountsOffice.objects.all().filter(student_id=user.id))
	global cleared
	cleared = student.cleared
	if library_items == 0 and workshop_items == 0 and mustso_items == 0 and laboratories_items == 0 and hod_items == 0 and catering_office_items == 0 and sports_games_items == 0 and accomodation_items == 0 and accounts_office_items == 0:
		cleared = True
		student.save()	
	context = { 'cleared': cleared }
	template_name = 'students/home.html'
	return render(request, template_name, context)


# @login_required
@student_required
def ProfileUpdate(request):
	user = request.user
	student = Student.objects.get(user=user)
	if request.method == "POST":
		u_form = UserUpdateForm(request.POST, instance=request.user)
		p_form = ProfileUpdateForm(request.POST, instance=request.user.student)
		if u_form.is_valid() and p_form.is_valid():
			user = u_form.save()
			student = p_form.save(commit=False)
			student.user = user
			student.save()
			messages.success(request, f'Your account has been successfully updated')
			return redirect('students:student-home')
	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.student)
				
	context = { 
		'u_form' : u_form,
		'p_form' : p_form,
		'cleared' : cleared
	}
	template_name = 'students/profileupdate.html'
	return render(request, template_name, context)



####################### Items Views ################################
@student_required
def items_urls(request):
	user = request.user
	student = Student.objects.get(user=user)
	context = { 'cleared' : cleared }	
	template_name = 'students/items-urls.html'
	return render(request, template_name, context)	


@student_required	
def library_items(request):	
	items =[]
	user = request.user
	student = Student.objects.get(user=user)
	students = Library.objects.all().filter(student_id =user.id)
	# print(students)
	for student in students:
		items.append(student.item)
	context = { 'items': items, 'cleared': cleared }	
	template_name = 'students/items-list.html'
	return render(request, template_name, context)


@student_required	
def workshop_items(request):
	items =[]
	user = request.user
	student = Student.objects.get(user=user)
	# print(user.id)
	students = Workshop.objects.all().filter(student_id =user.id)
	# print(students)
	for student in students:
		items.append(student.item)
	context = { 'items': items, 'cleared': cleared }	
	template_name = 'students/items-list.html'
	return render(request, template_name, context)


@student_required	
def mustso_items(request):
	items =[]
	user = request.user
	student = Student.objects.get(user=user)
	# print(user.id)
	students = MustSo.objects.all().filter(student_id =user.id)
	# print(students)
	for student in students:
		items.append(student.item)
	context = { 'items': items, 'cleared': cleared }	
	template_name = 'students/items-list.html'
	return render(request, template_name, context)


@student_required	
def laboratories_items(request):
	items =[]
	user = request.user
	student = Student.objects.get(user=user)
	# print(user.id)
	students = Laboratories.objects.all().filter(student_id =user.id)
	# print(students)
	for student in students:
		items.append(student.item)
	context = { 'items': items, 'cleared': cleared }	
	template_name = 'students/items-list.html'
	return render(request, template_name, context)


@student_required	 
def hod_items(request):
	items =[]
	user = request.user
	student = Student.objects.get(user=user)
	# print(user.id)
	students = HeadOfDepartment.objects.all().filter(student_id =user.id)
	# print(students)
	for student in students:
		items.append(student.item)
	context = { 'items': items, 'cleared': cleared }	
	template_name = 'students/items-list.html'
	return render(request, template_name, context)


@student_required	
def catering_office_items(request):
	items =[]
	user = request.user
	student = Student.objects.get(user=user)
	# print(user.id)
	students = CateringOffice.objects.all().filter(student_id =user.id)
	# print(students)
	for student in students:
		items.append(student.item)
	context = { 'items': items, 'cleared': cleared }	
	template_name = 'students/items-list.html'
	return render(request, template_name, context)


@student_required	
def sports_games_items(request):
	items =[]
	user = request.user
	student = Student.objects.get(user=user)
	# print(user.id)
	students = SportsGames.objects.all().filter(student_id =user.id)
	# print(students)
	for student in students:
		items.append(student.item)
	context = { 'items': items, 'cleared': cleared }	
	template_name = 'students/items-list.html'
	return render(request, template_name, context)


@student_required	
def accomodation_items(request):
	items =[]
	user = request.user
	student = Student.objects.get(user=user)
	# print(user.id)
	students = Accomodation.objects.all().filter(student_id =user.id)
	# print(students)
	for student in students:
		items.append(student.item)
	context = { 'items': items, 'cleared': cleared }	
	template_name = 'students/items-list.html'
	return render(request, template_name, context)


@student_required	
def accounts_office_items(request):
	items =[]
	user = request.user
	student = Student.objects.get(user=user)
	# print(user.id)
	students = AccountsOffice.objects.all().filter(student_id =user.id)
	# print(students)
	for student in students:
		items.append(student.item)
	context = { 'items': items, 'cleared': cleared }	
	template_name = 'students/items-list.html'
	return render(request, template_name, context)
	

################### Request View #####################
@student_required
def request_dos(request):
	user = request.user
	student = Student.objects.get(user=user)
	if request.method == 'POST':
		student.request = True
		student.save()
		messages.success(request, f'Request has been sent to Dean Of Students')
		return redirect('students:student-home')
	context = { 'cleared' : cleared }	
	template_name = 'students/request-dos.html'
	return render(request, template_name, context)	

templates/students/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block side-nav %}
	<div class="student-sidebar">
		<a href="{% url 'students:student-update' %}">Profile<i class="flaticon-user" style="margin-left:100px;"></i></a>
		<a href="{% url 'students:items-urls' %}">Items<i class="flaticon-inventory" style="margin-left:108px;"></i></a>
		{% if cleared %}
		<a href="{% url 'students:request-dos' %}">Request to DOS<img src="{% static 'img/bootstrap-icons/check-circle-fill.svg' %}" alt='student' height="25" width="25" style="margin-left:49px;padding-bottom:3px;"></a>
		{% endif %}
	</div>
{% endblock %}
{% block content%}
	
{% endblock %}

templates/students/items-list.html
{% extends 'base.html' %}
{% load static %}


{% block side-nav %}
	<div class="student-sidebar">
		<a href="{% url 'students:student-update' %}">Profile<i class="flaticon-user" style="margin-left:100px;"></i></a>
		<a href="{% url 'students:items-urls' %}">Items<i class="flaticon-inventory" style="margin-left:100px;"></i></a>
	</div>
{% endblock %}

{% block content %}
	<table class="table ">
		  <thead>
		    <tr>
		      <th scope="col">Items</th>
		    </tr>
		  </thead>
		  <tbody>
		  		{% if items %}
					{% for item in items %}
					<tr>
						<td>{{item}}</td>
					</tr>
					{% endfor %}
				{% else %}
					<tr>
						<td style="color:grey;">0 items</td>	
					</tr>
				{% endif %}	
		  </tbody>
	</table>		
{% endblock %}

templates/students/items-urls.html
{% extends 'base.html' %}
{% load static %}


{% block side-nav %}
	<div class="student-sidebar">
		<a href="{% url 'students:student-update' %}">Profile<i class="flaticon-user" style="margin-left:100px;"></i></a>
		<a href="{% url 'students:items-urls' %}">Items<i class="flaticon-inventory" style="margin-left:108px;"></i></a>
		{% if cleared %}
		<a href="{% url 'students:request-dos' %}">Request to DOS<img src="{% static 'img/bootstrap-icons/check-circle-fill.svg' %}" alt='student' height="25" width="25" style="margin-left:49px;padding-bottom:3px;"></a>
		{% endif %}
	</div>
{% endblock %}


{% block content %}
	<table class="table ">
		  <thead>
		    <tr>
		      <th scope="col">Departments</th>
		    </tr>
		  </thead>
		  <tbody>
				<tr>
					<td id="t-item"><a href="{% url 'students:library-items' %}">Library<a></td>
				</tr>
				<tr>
					<td id="t-item"><a href="{% url 'students:workshop-items' %}">Workshop<a></td>
				</tr>
				<tr>
					<td id="t-item"><a href="{% url 'students:mustso-items' %}">MustSo<a></td>
				</tr>
				<tr>
					<td id="t-item"><a href="{% url 'students:laboratories-items' %}">Laboratories<a></td>
				</tr>
				<tr>
					<td id="t-item"><a href="{% url 'students:hod-items' %}">Head Of Deapartment<a></td>
				</tr>
				<tr>
					<td id="t-item"><a href="{% url 'students:catering-office-items' %}">Catering<a></td>
				</tr>
				<tr>
					<td id="t-item"><a href="{% url 'students:sports-games-items' %}">Sports and Games<a></td>
				</tr>
				<tr>
					<td id="t-item"><a href="{% url 'students:accomodation-items' %}">Accomodation<a></td>
				</tr>
				<tr>
					<td id="t-item"><a href="{% url 'students:accounts-office-items' %}">Accounts Office<a></td>
				</tr>										
		  </tbody>
	</table>	
{% endblock %}

templates/students/profileupdate.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block side-nav %}
	<div class="student-sidebar">
		<a href="{% url 'students:student-update' %}">Profile<i class="flaticon-user" style="margin-left:100px;"></i></a>
		<a href="{% url 'students:items-urls' %}">Items<i class="flaticon-inventory" style="margin-left:108px;"></i></a>
		{% if cleared %}
		<a href="{% url 'students:request-dos' %}">Request to DOS<img src="{% static 'img/bootstrap-icons/check-circle-fill.svg' %}" alt='student' height="25" width="25" style="margin-left:49px;padding-bottom:3px;"></a>
		{% endif %}
	</div>
{% endblock %}
{% block content%}
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Update Profile</legend>
			{{u_form | crispy}}
			{{p_form | crispy}}
		</fieldset>
		<div class="form-group">
			<button class="btn-outline-info btn-lg" type="submit">Update</button>
		</div>
	</form>
{% endblock %}

templates/students/request-dos.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block side-nav %}
	<div class="student-sidebar">
		<a href="{% url 'students:student-update' %}">Profile<i class="flaticon-user" style="margin-left:100px;"></i></a>
		<a href="{% url 'students:items-urls' %}">Items<i class="flaticon-inventory" style="margin-left:108px;"></i></a>
		{% if cleared %}
		<a href="{% url 'students:request-dos' %}">Request to DOS<img src="{% static 'img/bootstrap-icons/check-circle-fill.svg' %}" alt='student' height="25" width="25" style="margin-left:49px;padding-bottom:3px;"></a>
		{% endif %}
	</div>
{% endblock %}
{% block content%}
	<p style="font-size:20px;">Are you sure you want to send a request to DOS?</p>
	<form method="POST">
		{% csrf_token %}
		<div class="form-group">
			<button class="btn-outline-success btn-lg " type="submit">Send</button>
		</div>		
	</form> 
{% endblock %}