accounts/urls.py
from django.urls import path
from accounts.views import students, teachers


app_name = 'accounts'

urlpatterns = [
	# path('home/', teachers.home_view, name='home'),
	path('login/student/', students.login_view, name='student-login'),
	path('login/teacher/', teachers.login_view, name='teacher-login'),
	path('logout/teacher/', teachers.logout_view, name='logout-teacher'),
	path('logout/student/', students.logout_view, name='logout-student'),
	#path('home_students', students.home_view, name='home'),
	path('signup/teachers/', teachers.TeacherSignupView.as_view(), name='teacher_signup'),
	path('signup/students/', students.StudentSignupView, name='student_signup'),
]

clearance_system/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
	path('admin/', admin.site.urls),
	path('accounts/', include('accounts.urls')),
    path('departments/', include('departments.urls')),
    path('students/', include('students.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.utils import timezone




class User(AbstractUser):
	is_student = models.BooleanField(default=False)
	is_teacher = models.BooleanField(default=False)
	

class Student(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
	course_name = models.CharField(max_length=100)
	id_number = models.CharField(max_length=15)
	cleared = models.BooleanField(default=False)
	request = models.BooleanField(default=False)


	# def get_absolute_url(self):
	# 	return reverse('accounts:phme', args=[self.id])


	def __str__(self):
		return f"{self.user.first_name} {self.user.last_name}"


class DepartmentOfficer(models.Model):

	CHOICES = (
		('Library','Library'),
		('Workshop','Workshop'),
		('MustSo','MustSo'),
		('Laboratories','Laboratories'),
		('Head Of Department','Head Of Department'),
		('Catering Office','Catering Office'),
		('Sports and Games','Sports and Games'),
		('Accomodation','Accomodation'),
		('Accounts Office','Accounts Office'),
		('Dean Of Students','Dean Of Students'),
		('Accounts Officer','Accounts Officer'),
		('Director Of Undergraduates','Director Of Undergraduates')
	)


	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
	department_name = models.CharField(max_length=100, choices=CHOICES)

	def __str__(self):
		return self.department_name

# class Department(models.Model):
# 	officer_name = models.CharField(max_length=100)
# 	department_name = models.CharField(max_length=100)
# 	clearance_item = models.CharField(max_length=200)
# 	student = models.ForeignKey(Student, on_delete=models.CASCADE)

# 	def __str__(self):
# 		return self.department_name


# @receiver(post_save, sender=User)
# def create_user(sender,instance,created,**kwargs):
# 	if created:
# 		Student.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user(sender,instance,created, **kwargs):
# 	instance.student.save()							

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.contrib.auth import get_user_model
from .models import User, Student
#User = get_user_model()

class TeacherSignupForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		model = User
		
	def save(self,commit=True):
		user = super().save(commit=False)
		user.is_teacher = True
		if commit:
			user.save()
		return user		


class StudentSignupForm(UserCreationForm):

	class Meta(UserCreationForm.Meta):
		model = User
		fields = ['username','first_name','last_name','email']

	@transaction.atomic
	def save(self, **kwargs):
		user = super().save(commit=False)
		user.is_student = True
		user.save()
		# student = Student.objects.create(user=user)
		return user


class StudentProfileForm(forms.ModelForm):
	course_name = forms.CharField(max_length=150)
	id_number = forms.CharField(max_length=15)

	class Meta(forms.ModelForm):
		model = Student
		fields = ('course_name','id_number')


class LoginForm(forms.Form):
	username = forms.CharField(max_length=150)
	password = forms.CharField(widget=forms.PasswordInput())

accounts/views/students.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect,render
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from ..forms import StudentSignupForm,LoginForm, StudentProfileForm
from ..models import User, Student
from django.contrib import messages

#User = get_user_model()


# class StudentSignupView(CreateView):
# 	model = User
# 	form_class = StudentSignupForm
# 	template_name = 'accounts/signup.html'
	
# 	def get_context_data(self,**kwargs):
# 		kwargs['user_type'] = 'student'
# 		return super().get_context_data(**kwargs)

# 	def form_valid(self,form):
# 		user = form.save()
# 		login(self.request, user)
# 		return redirect('accounts:home')	


def StudentSignupView(request, *args):
	if request.method == 'POST':
		signup_form = StudentSignupForm(request.POST or None)
		profile_form = StudentProfileForm(request.POST or None)
		if signup_form.is_valid() and profile_form.is_valid():
			user = signup_form.save()
			student = profile_form.save(commit=False)
			student.user = user
			student.save()
			messages.success(request, f'Account created for {user.first_name}')
			return redirect('students:student-home')
	else:
		signup_form = StudentSignupForm()
		profile_form = StudentProfileForm()

	template_name = 'accounts/signup.html'
	context = {'signup_form' : signup_form, 'profile_form': profile_form }
	return render(request, template_name, context)

			

# @login_required
# def home_view(request):
# 	return render(request,'students/home.html')


def login_view(request):
	form = LoginForm(request.POST or None)
	if request.method == 'POST': 
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(request, username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect('students:student-home')
			else:
				print("User not found")	
	return render(request, 'accounts/login.html',{ 'form': form})		

def logout_view(request):
	logout(request)
	return redirect('accounts:student-login')	



#message.debug
#message.info
#message.success
#message.warning
#message.error

accounts/views/teachers.py
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect,render
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from ..forms import TeacherSignupForm, LoginForm
from ..models import User
from django.contrib import messages

#User = get_user_model()


class TeacherSignupView(CreateView):
	model =  User
	form_class = TeacherSignupForm
	template_name = 'accounts/signup.html'


	def get_context_data(self, **kwargs):
		kwargs['user_type'] = 'teacher'
		# print(self.request.resolver_match.route)
		return super().get_context_data(**kwargs)


	def form_valid(self, form):
		user = form.save()
		login(self.request, user)
		messages.success(self.request, f'Account created for {user.username}')
		return redirect('accounts:teacher-login')

		

# @login_required
# def home_view(request):
# 	return render(request,'accounts/home.html',{})


def login_view(request):
	# print(request.__dict__)
	# print(request.resolver_match.route)
	form = LoginForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():	
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(request, username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect('departments:upload')
			else:
				print("No user found")
	return render(request,'accounts/login.html',{"form":form})			

def logout_view(request):
	logout(request)
	return redirect('accounts:teacher-login')			

templates/accounts/home.html
<!DOCTYPE html>
<html>
	<head>
		<title>Home Page</title>
	</head>
	<body>
		<h1>SUCCESS!</h1>
		<a href="{% url 'accounts:logout-teacher' %}">Logout</a>
	</body>
</html>

templates/accounts/login.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">	
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'jquery/jquery.min.js' %}"></script>
	<title>Base Doc</title>
</head>

<body>
<div class="cont-special">
	<div class="cont-col-special">
	<div class="nav-cont-special">
		<div class="logo-special">
			<img src="{% static 'img/logo.jpeg' %}">
		</div>
		{% if request.resolver_match.route == 'accounts/login/teacher/' %}
		<div class="nav-center-special">
			<a href="{% url 'accounts:teacher_signup' %}">Signup</a>
		</div>
		{% else %}
		<div class="nav-center-special">
			<a href="{% url 'accounts:student_signup' %}">Signup</a>
		</div>
		{% endif %}		
	</div>
	<div class="content-cont-special">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Login</legend>
				{{form | crispy}}
			</fieldset>
			<div class="form-group">
				<button class="btn-outline-success btn-lg " type="submit">Login</button>
			</div>
		</form>
	</div>
	</div>
</div>
</body>	
</html>

templates/accounts/signup.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">	
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'jquery/jquery.min.js' %}"></script>
	<title>Base Doc</title>
</head>

<body>
<div class="cont-special">
	<div class="cont-col-special">
	<div class="nav-cont-special">
		<div class="logo-special">
			<img src="{% static 'img/logo.jpeg' %}">
		</div>
		{% if request.resolver_match.route == 'accounts/signup/teachers/' %}
		<div class="nav-center-special">
			<a href="{% url 'accounts:teacher-login' %}">Login</a>
		</div>
		{% else %}
		<div class="nav-center-special">
			<a href="{% url 'accounts:student-login' %}">Login</a>
		</div>
		{% endif %}				
	</div>
	<div class="content-cont-special">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Sign up</legend>
				{{form | crispy}}
				{{signup_form | crispy}}
				{{profile_form | crispy}}
			</fieldset>
			<div class="form-group">
				<button class="btn-outline-info btn-lg " type="submit">Signup</button>
			</div>
		</form>
	</div>
	</div>
</div>
</body>	
</html>