accounts/urls.py
from django.urls import path
from accounts.views import students, teachers


app_name = 'accounts'

urlpatterns = [
	# path('home/', teachers.home_view, name='home'),
	path('login/student/', students.login_view, name='student-login'),
	path('login/teacher/', teachers.login_view, name='teacher-login'),
	path('logout/teacher/', teachers.logout_view, name='logout-teacher'),
	path('logout/student/', students.logout_view, name='logout-student'),
	#path('home_students', students.home_view, name='home'),
	path('signup/teachers/', teachers.TeacherSignupView.as_view(), name='teacher_signup'),
	path('signup/students/', students.StudentSignupView, name='student_signup'),
]

clearance_system/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
	path('admin/', admin.site.urls),
	path('accounts/', include('accounts.urls')),
    path('departments/', include('departments.urls')),
    path('students/', include('students.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">	
	<link rel="stylesheet" type="text/css" href="{% static 'icons/flaticon.css' %}">		
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'jquery/jquery.min.js' %}"></script>
	<title>Base Doc</title>
</head>
<body>
	<div class="cont">
		<div class="side-bar">
			<div class="logo">
				<img src="{% static 'img/logo.jpeg' %}">
			</div>
			<div class="side-nav">
				{% block side-nav%} 
				{% endblock %}
			</div>
		</div>
		<div class="cont-col">
			<div class="nav-cont">
				<div class="nav-center">
					{% if user.is_student %}
					<a href="#">{{user.username}}</a>
					<a href="#">{{user.student.id_number}}</a>	
					<a href="{% url 'accounts:logout-student' %}">Logout</a>
					{% else %}
					<a href="#">{{user.username}}</a>
					<a href="{% url 'accounts:logout-teacher' %}">Logout</a>
				{% endif %}					
				</div>
			</div>
			<div class="content-cont">
				{% if messages %}
					{% for message in messages %}
					<div class="alert alert-{{ message.tags }}">
						{{ message }}
					</div>
					{% endfor %}
				{% endif %}	
				{% block content%}
				{% endblock %}
		</div>
	</div>
	{% block footer %}
		<script type="text/javascript" src="{% static 'js/main.js' %}"></script>	
	{% endblock %}
</body>
</html>